spring: 
  config:
    import: application-data.yaml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  freemarker: 
    template-loader-path: classpath:/templates
    suffix: .ftlh
    cache: false
    
---    
# 언어설정
spring:
  messages:
    basename: messages/message
    encoding: UTF-8
