spring: 
  config:
    import: 
      - application-data.yaml
      - application-mail.yaml
      - classpath:/mail/yaml/mail-template-ko.yaml
      - classpath:/mail/yaml/mail-template-jp.yaml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  freemarker: 
    template-loader-path: classpath:/templates
    suffix: .ftlh
    cache: false
    
---    
# 언어설정
spring:
  messages:
    basename: messages/message
    encoding: UTF-8
    
---
# 기타 고정값
value:
  tmpCode:
    limit: 20 #분 단위
