spring: 
  config:
    import: 
      - application-data.yaml
      - application-mail.yaml
      - classpath:/mail/yaml/mail-template-ko.yaml
      - classpath:/mail/yaml/mail-template-jp.yaml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  freemarker: 
    template-loader-path: classpath:/templates
    suffix: .ftlh
    cache: false
    
---    
# 언어설정
spring:
  messages:
    basename: messages/message
    encoding: UTF-8
    
---
# 기타 고정값
value:
  hashing:
    times: 100 #기본 해싱 반복 횟수
    salt: "eK3jdn8Sl1kj"
  tmpCode:
    limit: 
      minutes: 20 #분 단위
      times: 5 #반복해서 보낸 횟수
  member:
    password:
      saltLength: 16
      hashingTimes: 20
  
