spring:
  mail:
    host: smtp.office365.com
    port: 587
    username: myyk.system@outlook.com
    password: Tractatus1#
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true