<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<#include "/lib.ftlh">
<title><@msg "global.title"/></title>
<style>
.code-holer {
    color: var(--soft-black);
    width: 100%;
    letter-spacing: 1rem;
}
</style>
</head>
<#include "/header.ftlh">
<body>
  <div id="content">
    <div id="wrapper">

    hello, world!






    </div>
  </div>
</body>
<#include "/footer.ftlh">
<script>

</script>

<script src="/js/member.js"></script>
</html>
