<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<#include "/lib.ftlh"> 
<title><@spring.message "account.dashboard.title"/></title>
</head>
<#include "/global/header.ftlh">
<body>
	<h1 class="title">
		<@spring.message "member.create.input.title"/>
	</h1>
	<div>
	d
	</div>
	<div>
	f
	</div>
</body>
<#include "/global/footer.ftlh">
<script type="text/javascript">

</script>
</html>